name: PdfScribeInstallerBuild

on: workflow_dispatch

jobs:
  Build-Installer:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - run: |
        $folderPath = ".\PdfScribeInstall\bin\x64\Release\en-us"
        if (-not (Test-Path -Path $folderPath)) {
            New-Item -Path $folderPath -ItemType Directory
            Write-Output "Folder Created Successfully!"
        }
        else {
            Write-Output "Folder already exists!"
        }
      shell: pwsh
    
    - name: build the imagefile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run:  publishrelease.bat
      shell: cmd
      
    - name: upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        path: 
          ".\\PdfScribeInstall\\bin\\x64\\Release\\en-us\\*.msi"
